# Generated by Django 3.0.8 on 2020-09-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_serv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Svg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='番号')),
                ('overview', models.TextField(blank=True, max_length=100, verbose_name='説明')),
                ('svg_tags', models.TextField(blank=True, verbose_name='SVG')),
            ],
            options={
                'verbose_name': 'SVG付き記録メモ',
                'verbose_name_plural': 'SVG付き記録メモ一覧',
            },
        ),
        migrations.AlterModelOptions(
            name='my_svg',
            options={},
        ),
        migrations.AddField(
            model_name='my_data',
            name='svg_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='svgno'),
        ),
    ]
