# Generated by Django 3.0.8 on 2020-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_serv', '0002_auto_20200914_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg_Svg',
        ),
        migrations.AlterModelOptions(
            name='my_svg',
            options={'verbose_name': 'SVG付き記録メモ', 'verbose_name_plural': 'SVG付き記録メモ一覧'},
        ),
        migrations.AddField(
            model_name='my_data',
            name='dfg',
            field=models.BooleanField(default=False, verbose_name='DEL'),
        ),
        migrations.AlterField(
            model_name='my_data',
            name='svg_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='svg_no'),
        ),
    ]
