# Generated by Django 3.0.8 on 2021-01-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_serv', '0004_auto_20210101_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_Index',
            new_name='My_Ind',
        ),
    ]
