# Generated by Django 3.0.8 on 2021-01-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_serv', '0005_auto_20210101_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='番号')),
                ('kind', models.CharField(blank=True, max_length=30, verbose_name='種類')),
                ('dfg', models.BooleanField(default=False, verbose_name='DEL')),
                ('svg_no', models.IntegerField(blank=True, null=True, verbose_name='svg_no')),
                ('theme', models.CharField(blank=True, max_length=30, verbose_name='課題名')),
                ('bunrui1', models.CharField(blank=True, max_length=30, verbose_name='分類１')),
                ('bunrui2', models.CharField(blank=True, max_length=30, verbose_name='分類２')),
                ('bunrui3', models.CharField(blank=True, max_length=30, verbose_name='分類３')),
                ('day_regist', models.CharField(blank=True, max_length=30, verbose_name='登録日')),
                ('day_modify', models.CharField(blank=True, max_length=30, verbose_name='修正日')),
                ('author', models.CharField(blank=True, max_length=30, verbose_name='著者')),
                ('overview', models.TextField(blank=True, verbose_name='概要')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('keywords', models.TextField(blank=True, verbose_name='KeyWd')),
            ],
        ),
        migrations.RenameModel(
            old_name='My_Ind',
            new_name='My_Index',
        ),
    ]
