# Generated by Django 3.0.8 on 2021-01-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_serv', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
