# Generated by Django 3.0.8 on 2021-04-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_serv', '0010_auto_20210201_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_CnSvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='番号')),
                ('kind', models.CharField(blank=True, max_length=30, verbose_name='種類')),
                ('dfg', models.BooleanField(default=False, verbose_name='DEL')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='著者')),
                ('cnsvg_nk', models.IntegerField(blank=True, null=True, verbose_name='csvg_nk')),
                ('svg_tags', models.TextField(blank=True, verbose_name='SVG')),
            ],
        ),
        migrations.AddField(
            model_name='my_data',
            name='cnsvg_nk',
            field=models.IntegerField(blank=True, null=True, verbose_name='csvg_nk'),
        ),
        migrations.AddField(
            model_name='my_data',
            name='cnsvg_nums',
            field=models.IntegerField(blank=True, null=True, verbose_name='csvg_nums'),
        ),
        migrations.AddField(
            model_name='my_svg',
            name='dfg',
            field=models.BooleanField(default=False, verbose_name='DEL'),
        ),
    ]
