# Generated by Django 3.0.8 on 2021-04-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_serv', '0011_auto_20210428_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_cnsvg',
            name='mfg',
            field=models.BooleanField(default=False, verbose_name='Modf'),
        ),
        migrations.AddField(
            model_name='my_data',
            name='mfg',
            field=models.BooleanField(default=False, verbose_name='Modf'),
        ),
        migrations.AddField(
            model_name='my_svg',
            name='mfg',
            field=models.BooleanField(default=False, verbose_name='Modf'),
        ),
    ]
