# Generated by Django 3.0.8 on 2021-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_serv', '0013_auto_20210501_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_cnsvg',
            name='cnsvg_nk',
        ),
        migrations.RemoveField(
            model_name='my_cnsvg',
            name='name',
        ),
        migrations.RemoveField(
            model_name='my_data',
            name='cnsvg_nk',
        ),
        migrations.RemoveField(
            model_name='my_svg',
            name='cnsvg_nk',
        ),
        migrations.RemoveField(
            model_name='my_svg',
            name='name',
        ),
        migrations.AddField(
            model_name='my_data',
            name='cnsvg_tags',
            field=models.CharField(blank=True, max_length=300, verbose_name='cnsvg_tags'),
        ),
    ]
